#################################################################
############### GTlab Standard Pipeline Version 2.1.0 ###########
#################################################################
#
# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR)
# SPDX-License-Identifier: MPL-2.0+

# Variables that are defined globally for the pipeline
variables:
  PIPELINEVERSION: "2.1.0"
  GIT_SUBMODULE_STRATEGY: none
  
  STABLE_BRANCHES: /^master$/
  

include:
  - project: 'gtlab/public/development-tools/gitlab-templates'
    file: '/ci-templates/.ci-templates-cmake-1.0.yml'

stages:
  - build
  - package
  - deploy

# build on Windows system
build-windows:
  stage: build
  extends: 
    - .build-win_20
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install-msvc2019
    - cmake --build build --target install
  after_script:
    - cd install-msvc2019
    - '& "$env:QT_INSTALL_PATH\bin\windeployqt.exe" bin\GtModuleGenerator.exe --plugindir=bin/plugins'
    
# build on Linux system
build-linux:
  stage: build
  extends: 
    - .build-linux_20
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install-linux
    - cmake --build build --target install


package-windows:
  stage: package
  extends: 
    - .build-linux_20
  needs:
    - build-windows
  script:
    - mv install-msvc2019 gtmodulegenerator-msvc2019
    - mv gtmodulegenerator-msvc2019/bin/*  gtmodulegenerator-msvc2019/
    - rm -rf  gtmodulegenerator-msvc2019/bin
    - rm -rf gtmodulegenerator-msvc2019/translations
    - tar czvf gtmodulegenerator-msvc2019.tar.gz gtmodulegenerator-msvc2019
  artifacts:
    name: "gtmodulegenerator-msvc2019"
    paths: ["gtmodulegenerator-msvc2019.tar.gz"]


package-linux:
  stage: package
  extends: 
    - .build-linux_20
  needs:
    - build-linux
  before_script:
    - apt install -y patchelf
    - 'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${CI_API_V4_URL}/projects/7584/packages/generic/cqtdeployer/1.6.2365/cqtdeployer_linux64.tar.gz'
    - tar xf cqtdeployer_linux64.tar.gz
    - export PATH=`pwd`/cqtdeployer_linux64:$PATH
  script:
    # linux package
    - mv install-linux gtmodulegenerator-linux && cd gtmodulegenerator-linux
    - CQtDeployer.sh -qmake $QMAKE_PATH -bin bin/GtModuleGenerator -targetDir . noTranslations -libDir $QT_INSTALL_PATH/lib/ 
    - rm GtModuleGenerator.sh && patchelf --set-rpath '$ORIGIN/../lib' bin/GtModuleGenerator
    - cd .. && tar czvf gtmodulegenerator-linux.tar.gz gtmodulegenerator-linux
  artifacts:
    name: "gtmodulegenerator-linux"
    paths: ["gtmodulegenerator-linux.tar.gz"]
