########################################################
############### Pipeline  ############
########################################################
#  CATEGORY: 00_tools
#  PROFILENAME: GtModuleGenerator.pro
#  TARGETNAME: GtModuleGenerator
#  SUBDIRNAME: ModuleGenerator

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build
  - copy

# Windows build
windowsBuild:
  stage: build
  before_script:
    - git submodule sync
    - git submodule update --init
  script:
    - .\pipeline-scripts\build\build-512-tools.bat 1>buildLog512.txt
  tags:
    - Win10
  artifacts:
    paths:
      - build\$TARGETNAME.exe
      - buildLog512.txt
    expire_in: 1 week
    when: always
  variables:
    BUILDMODE: release
    #PROFILENAME: GtModuleGenerator.pro

# Linux build
linuxBuild:
  stage: build 
  tags:
    - Linux
  script:
    - /opt/Qt/5.12.5/gcc_64/bin/qmake $PROFILENAME -spec linux-g++ CONFIG+=$BUILDMODE
    - make clean
    - make -j 20 |& tee linuxBuild.txt
  artifacts:
    paths:
      - build/$TARGETNAME
    when: always
    expire_in: 1 week
  variables:
    BUILDMODE: release
    #PROFILENAME: GtModuleGenerator.pro
 
copyForDeploymentWin:
  stage: copy
  before_script:
    - git submodule sync
    - git submodule update --init
  script:
    - .\pipeline-scripts\deploy\copyTool.bat
  needs:
    - windowsBuild
  dependencies:
    - windowsBuild
  tags:
    - Win10
  only:
    - tags
  variables:
    PLATFORMNAME:  windows
    RELEASESTATUS: tools
#    SUBDIRNAME: ModuleGenerator
#    CATEGORY: 00_tools

copyForDeploymentLinux:
  stage: copy
  before_script:
    - git submodule sync
    - git submodule update --init
  script:
    - .\pipeline-scripts\deploy\copyTool.bat
  needs:
    - linuxBuild
  dependencies:
    - linuxBuild
  tags:
    - Win10
  only:
    - tags
  variables:
    PLATFORMNAME:  linux
    RELEASESTATUS: tools
#    SUBDIRNAME: ModuleGenerator
#    CATEGORY: 00_tools
