#include "class_specification_widget.h"

#include "function_specification_widget.h"
#include "module_generator_settings.h"
#include "module_generator_logger.h"

#include <QGridLayout>
#include <QLabel>
#include <QLineEdit>
#include <QFrame>
#include <QRegularExpressionValidator>

const QString S_CLASS_NAME_LABEL =
        QStringLiteral("Class name:");
const QString S_FILE_NAME_LABEL =
        QStringLiteral("File name:");
const QString S_OBJECT_NAME_LABEL =
        QStringLiteral("Object name:");

const QString S_AUTO_GENERATED_TOOLTIP =
        QStringLiteral("autogenerated using the object name");

ClassSpecificationWidget::ClassSpecificationWidget(FunctionStruct& function,
                                                   ModuleGeneratorSettings* settings,
                                                   QWidget* parent) :
    QWidget(parent),
    m_functionStruct(function),
    m_settings(settings)
{
    m_nameValidator = new QRegularExpressionValidator(ModuleGeneratorSettings::REG_OBJECT_NAME, this);

    m_baseLayout = new QGridLayout();

    m_classNameLabel = new QLabel(S_CLASS_NAME_LABEL);
    m_objectNamelabel = new QLabel(S_FILE_NAME_LABEL);
    m_fileNameLabel = new QLabel(S_OBJECT_NAME_LABEL);

    m_classNameEdit = new QLineEdit();
    m_objectNameEdit = new QLineEdit();
    m_fileNameEdit = new QLineEdit();

    m_classNameEdit->setEnabled(false);
    m_classNameEdit->setToolTip(S_AUTO_GENERATED_TOOLTIP);
    m_fileNameEdit->setEnabled(false);
    m_fileNameEdit->setToolTip(S_AUTO_GENERATED_TOOLTIP);

    m_baseLayout->addWidget(m_objectNamelabel, 0, 0);
    m_baseLayout->addWidget(m_objectNameEdit, 0, 1);
    m_baseLayout->addWidget(m_classNameLabel, 1, 0);
    m_baseLayout->addWidget(m_classNameEdit, 1, 1);
    m_baseLayout->addWidget(m_fileNameLabel, 2, 0);
    m_baseLayout->addWidget(m_fileNameEdit, 2, 1);

    m_objectNameEdit->setValidator(m_nameValidator);

    m_functionSpecificationWidget = Q_NULLPTR;

    auto* baseClass = function.baseClass;

    if (baseClass != Q_NULLPTR)
    {
        m_functionSpecificationWidget = new FunctionSpecificationWidget(baseClass->functions, settings);

        if (m_functionSpecificationWidget->isEmpty())
        {
           LOG_INSTANCE("empty function widget!", ModuleGeneratorLogger::Type::Warning);

            delete m_functionSpecificationWidget;
            m_functionSpecificationWidget = Q_NULLPTR;
        }
        else
        {
            QFrame* line =new QFrame();
            line->setFrameShape(QFrame::HLine);
            line->setFrameShadow(QFrame::Sunken);

            m_baseLayout->addWidget(line, 3, 0, 1, 3);
            m_baseLayout->addWidget(m_functionSpecificationWidget, 4, 0, 1, 3);
        }
    }

    auto* spacer = new QSpacerItem(1, 1, QSizePolicy::Minimum, QSizePolicy::MinimumExpanding);

    m_baseLayout->addItem(spacer, 5, 0, 1, 3);

    setLayout(m_baseLayout);

    // signals
    connect(m_objectNameEdit, SIGNAL(textChanged(QString)),
            this, SLOT(onEditedObjectName(QString)));
}

ClassStruct
ClassSpecificationWidget::classImplementation()
{
    ClassStruct implementedClass;
    implementedClass.className   = m_classNameEdit->text();
    implementedClass.fileName    = m_fileNameEdit->text();
    implementedClass.objectName  = m_objectNameEdit->text().simplified();

    if (m_functionSpecificationWidget != Q_NULLPTR)
    {
        m_functionSpecificationWidget->setImplementation();
    }

    return implementedClass;
}

void
ClassSpecificationWidget::closeEvent(QCloseEvent* event)
{
    event->accept();

    emit hidden();
}

void
ClassSpecificationWidget::onEditedObjectName(QString name)
{
    m_fileNameEdit->setText(m_settings->fileNamingScheme(name));
    m_classNameEdit->setText(m_settings->classNamingScheme(name));
}
